name: CI
on:
  pull_request:
    branches: [ master, develop ]
    types: [opened, assigned, edited, synchronize, reopened]
jobs:
  check_changelog:
    if: "! contains(toJSON(github.event.pull_request.title), '[skip-changelog]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          markdown:
            - modified: 'CHANGELOG.MD'
    - name: Check if modified changelog is present
      if: ${{ steps.changes.outputs.markdown == 'false' }}
      run: |
        echo "Doesn't found a modified CHANGELOG.MD"
        exit 1