name: Check changelog
on:
  pull_request:
    branches: [ master ]
jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          markdown:
            - modified: 'CHANGELOG.md'
    if: steps.changes.outputs.src == 'false'
    run: exit 1
