name: Check changelog
on:
  pull_request:
    branches: [ master ]
jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          markdown:
            - modified: 'CHANGELOG.MD'
    - name: Validate
      if: ${{ steps.changes.outputs.markdown == 'false' }}
      run: exit 1
