name: Check changelog
on:
  pull_request:
    branches: [ master ]
jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "CHANGELOG.MD"
          allow_failure: true

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
